query-spotify/index.js
query-spotify/package-lock.json
query-spotify/package.json

adding code to authorize & query spotify

unnesting spotify query

---

front-end/index.html
front-end/quotes.json
front-end/styles.css

Implemented the UI for daily quote display in index.html and mocked the daily quote generation, pulling data from quotes.json. The script for this feature's implementation is located in index.html. As of now, every time the page is refreshed, a new quote is generated. Will fix this feature later on so that it generates a new quote every 24 hours instead.

Quote Display/Generation

---

front-end/index.html

Implemented logic to keep track of the current date and the quote associated with the day in order to ensure quote updates only happen every 24 hours at midnight EST. Addressed a bug with previous implementation of this feature.

Updated script to only change quote every 24 hours

---

front-end/feed-script.js
front-end/source/services/DatabaseFakeService.js
front-end/utility/submission-fetch.js

Merged mocking for feed screen and trending screen by adding getSubmission method to DatabaseFakeService class. Updated feed-script.js to reflect new architecture/structure.

Merge trending and feed screen mocking functions

---

front-end/index.html
front-end/originalDatabase.js

Created originalDatabase.js. Modified index.html to use these originalDatabase.js methods for indexedDB use, instead of using localStorage to keep track of the daily quote in index.html.

Created originalDatabase.js with general methods for indexedDB use

---

front-end/feed-script.js
front-end/feed.html
front-end/source/services/DatabaseFakeService.js
front-end/styles.css
front-end/utility/submission-fetch.js

Updated submission-fetch function to return "rotating" submissions. Updated feed-script.js to mimic fetching submissions from backend periodically, and re-rendering feed with new retrieved submissions.

Mocked continuous feed updates to feed UI

---

front-end/feed-script.js
front-end/feed.html
front-end/styles.css

Added a different view that will be displayed when 24-hour reset is carried out (or when no submissions are available to be displayed).

Added blank screen UI for 24-hour reset

---

front-end/index.html
front-end/search-song.js
front-end/styles.css

Added a "Submit" button to the interface to improve user flow by allowing users to land on the "feed" page after adding selected songs. Clicking the button will redirect users to the "Feed" page, ensuring a seamless transition. Also renamed previously "Saved" widget to "To Add".

Added submit button to To Add widget redirecting to Feed page

---

backend/query-spotify/spotify-routes.js

Spotify Query #69: using cookies to store authorization token

---

front-end/index.html

Utilized the following API endpoint (https://zenquotes.io/api/random) to generate random quotes. Modified the loadQuote() function in index.html to do so with the API instead of the prior implementation with mocked quote data. Additionally, added logic to ensure daily quote persistence (the same quote should be displayed for a given day).

Quotes API Integration (see PR #94) - renamed branch

---

front-end/index.html

Provided comments for code changes associated with Quotes API Integration

Quotes API Integration Comments

---

backend/routes/trending-routes.js
front-end/source/services/DatabaseFakeService.js

Changes:
- Create trending-routes.js
- Implemented routing calls for each summary statistic. 
Why:
- To support frontend/backend interfacing; allows front-end to get summary statistics for trending page (ie: trending songs, top contributors, individual with longest streak)

Trending Page Routes -- #88

---

backend/query-spotify/spotify-routes.js

Song Database Storage #69: storing track name & artist in DB

---

front-end/index.html
team/reports/mai-chi-le.md

Quote generation wasn't working on other people's devices, so debugged on Mai's computer.

Debugged quote generation error

---

backend/controller/SubmissionController.js
backend/index.js
backend/routes/history-routes.js

What was changed:
-Added history-routes.js, which creates an endpoint for the history page 
-Added getYourSubmissions() function to SubmissionController.js 
-Added history page in the frontend
Why:
-History page route necessary to service History page in the frontend

History Page Route #100:

---

backend/controller/SubmissionController.js
backend/model/SQLiteModel.js
backend/routes/feed-routes.js
front-end/feed-script.js

- **Related Issues:** #120 , #121 , #122 
- **Changes:**
- Added new Sequelize Method getSubsToday() to filter entries in database and retrieve submissions from the current day. 
- Added new GET route in `feed-routes.js` so that frontend has an endpoint to query to retrieve the current day's submissions. 
- Modified `feed-script.js` to query the new endpoint, so that user will be shown current day's submissions.

Feed UI -- Displays Current Day's Subs -- #122

---

backend/controller/SubmissionController.js
backend/routes/history-routes.js
front-end/SpotifyLogin.js
front-end/history.html
front-end/history.js
front-end/navbar.html

What was changed:
-Set up frontend logic to initialize history page
Why:
-This is a template that will eventually contain the appropriate middleware to fetch history page data and HTML to render a dynamic table

History page route #100

---

backend/controller/UserController.js
backend/index.js
backend/model/SQLiteModel.js
backend/query-spotify/spotify-routes.js
front-end/search-song.js
front-end/source/services/SpotifyAPIFakeService.js

Spotify Search Integration #70: integrating backend functionality w/ frontend search section

---

backend/controller/SubmissionController.js
backend/eventhub/Events.js
backend/index.js
backend/model/SQLiteModel.js
backend/routes/feed-routes.js

Related Issue: #142 
Description: 
- Added comments in files `index.js`, `feed-routes.js`, `SQLiteModel.js` and `SubmissionController.js` to finish explaining work that we completed in relation to the feed screen/UI.

Adding Comments to Feed UI Work

---

backend/controller/SubmissionController.js
backend/model/SQLiteModel.js
backend/routes/trending-routes.js
front-end/styles.css
front-end/trending-script.js
front-end/trending.html

-**Description:** Added summary statistic where user can see the top 3 artists from their previous submissions. Statistic is displayed in the trending UI. 
- **Issues:** #145 , #146 , #147 
- **Changes:** 
- Added method to query database in `SQLiteModel.js` and `SubmissionController.js`
- Added route in `trending-routes.js` to access database methods
- Updated trending UI to fetch from top 3 artists from backend and display it with the other summary statistics.

Added Get Top Artists Summary Statistic

---

front-end/feed-script.js

- **Description:** Some widgets would render incorrectly if the song or artist's name was too long. Now, when rendering widgets, if the text will not fit within the widget, it will truncate the text and add "..." to show the majority of the text while indicating that it is longer. This allows the widgets to render correctly regardless of text length. 
- **Issue:** #144

Fix Sizing Issue on Feed Widgets #144

---

front-end/saved-script.js

Added previously https://github.com/lucyzhang04/326Project/pull/151 functionality to add song to chosen Spotify playlist using a dropdown and "Add to Playlist" button for songs in "Saved" page front-end

Changed to Adding Songs to Playlist from Saved

---

backend/index.js
front-end/feed-script.js

- **Description:** Cleaning up commented out code snippets to follow best practices.

Cleaning up commented out code snippets 

---

backend/query-spotify/spotify-routes.js
front-end/saved-script.js

Added comments to code implemented for Milestone 4 (ong-adding-to-playlist feature in query-spotify/spotify-routes.js and saved-script.js).

Added comments to song-adding-to-playlist features

---

backend/query-spotify/spotify-routes.js

Removed unnecessary scopes to adhere to the principle of least privilege.

Edited scopes following least privilege principle
